Enum ClassType {
  Monthly
  Day
  Course
}

Enum ClassStatus {
	Pending
  Done
  Cancelled
  Delayed
}

enum PaymentStatus {
  Paid
  Due
  Unpaid
  Problem
}

enum PaymentType {
	Cash
	Bkash
	Bank
	Others
}


Table Teacher {
  id integer pk
  name string
  salary integer
}

Table Student {
  id integer pk
  name string
  address string
  phone string[]
  type ClassType
  amount integer
  teacher_id integer

  created_at datetime
  updated_at datetime
  deleted_at datetime
}

Table Class {
  id integer pk
  title integer 
  dated datetime
  duration time
  homework string
  notes string[]
  student_id integer

  created_at datetime
  updated_at datetime
  deleted_at datetime
}

Table Schedule {
  id integer pk
  schedule datetime
  preference datetime
  status ClassStatus
  teacher_id integer

  created_at datetime
  updated_at datetime
  deleted_at datetime
}

Table Payment {
  trx_id string pk // UUID
  amount integer
  status PaymentStatus
  session string
  type PaymentType
  from string 
  student_id integer

  created_at datetime
  updated_at datetime
  deleted_at datetime
}

Ref: "Class"."student_id" > "Student"."id"
Ref: "Payment"."student_id" > "Student"."id"
Ref: "Student"."teacher_id" > "Teacher"."id"
Ref: "Schedule"."teacher_id" > "Teacher"."id"

